Following this tutorial with a lot of visuals:
https://jalammar.github.io/visual-numpy/

Using NumPy: https://numpy.org/

In [2]:
import numpy as np

In [20]:
#Initalizing NumPy arrays (ndarray)

#From a Python list
ndarray_list = np.array([1,2,3])
print(ndarray_list)

#Ones, zeroes, or random between 0 and 1
print('np.ones(3) = ', np.ones(3))
print('np.zeros(3) = ', np.zeros(3))
print('np.random.random(3) = ', np.random.random(3))

[1 2 3]
np.ones(3) =  [1. 1. 1.]
np.zeros(3) =  [0. 0. 0.]
np.random.random(3) =  [0.64472401 0.94470244 0.67292081]


In [11]:
#ARRAY ARITHMETIC
data = np.array([1,2])
ones = np.ones(2)

print(data, ' + ', ones, ' = ', data + ones)
print(data, ' - ', ones, ' = ', data - ones)
print(data, ' * ', ones, ' = ', data * ones)
print(data, ' / ', ones, ' = ', data / ones)
print(data, ' * ', 1.6, ' = ', data * 1.6)

[1 2]  +  [1. 1.]  =  [2. 3.]
[1 2]  -  [1. 1.]  =  [0. 1.]
[1 2]  *  [1. 1.]  =  [1. 2.]
[1 2]  /  [1. 1.]  =  [1. 2.]
[1 2]  *  1.6  =  [1.6 3.2]


In [14]:
#INDEXING
data = np.array([1,2,3])
print('data[0] = ', data[0])
print('data[1] = ', data[1])
print('data[0:2] = ', data[0:2])
print('data[1:] = ', data[1:])

data[0] =  1
data[1] =  2
data[0:2] =  [1 2]
data[1:] =  [2 3]


In [16]:
#AGGREGATION
data = np.array([1,2,3])
print('data.max() = ', data.max())
print('data.min() = ', data.min())
print('data.sum() = ', data.sum())
print('data.prod() = ', data.prod())
print('data.std() = ', data.std())

data.max() =  3
data.min() =  1
data.sum() =  6
data.prod() =  6
data.std() =  0.816496580927726


In [24]:
#CREATING MATRICIES
matrix_lists = np.array([[1,2],[3,4]])
print(matrix_lists)

#Can use ones, zeros, and random as well - just pass in a tuple
print('\nnp.ones((3,2))\n', np.ones((3,2)))
print('\nnp.zeros((3,2))\n', np.zeros((3,2)))
print('\nnp.random.random((3,2))\n', np.random.random((3,2)))

[[1 2]
 [3 4]]

np.ones((3,2))
 [[1. 1.]
 [1. 1.]
 [1. 1.]]

np.zeros((3,2))
 [[0. 0.]
 [0. 0.]
 [0. 0.]]

np.random.random((3,2))
 [[0.33143634 0.40787852]
 [0.35374034 0.87420762]
 [0.47953813 0.2686969 ]]


In [31]:
#MATRIX ARITHMETIC
data = np.array([[1,2],[3,4]])
print('data')
print(data)

print('\ndata + np.ones((2,2))')
print(data + np.ones((2,2)))

#Same operation as above (by numpy broadcast rules)
print('\ndata + np.ones(2)')
print(data + np.ones(2))

data
[[1 2]
 [3 4]]

data + np.ones((2,2))
[[2. 3.]
 [4. 5.]]

data + np.ones(2)
[[2. 3.]
 [4. 5.]]


In [36]:
#DOT PRODUCT
data = np.array([1,2,3])
power_of_ten = np.array([[1,10],[100, 1000],[10000, 100000]])
print('data')
print(data)

print('\npower_of_ten')
print(power_of_ten)

print('\ndata.dot(powers_of_ten)')
print(data.dot(power_of_ten))

data
[1 2 3]

power_of_ten
[[     1     10]
 [   100   1000]
 [ 10000 100000]]

data.dot(powers_of_ten)
[ 30201 302010]


Explained Here:

![dotproduct](https://jalammar.github.io/images/numpy/numpy-matrix-dot-product-1.png)
![dotproduct](https://jalammar.github.io/images/numpy/numpy-matrix-dot-product-2.png)

In [48]:
#MATRIX INDEXING
data = np.array([[1,2], [3,4], [5,6]])
print('data')
print(data)

print('\ndata[row:row, col:col]')
print('data[0,1] = ', data[0,1])
print('\ndata[1:3]\n', data[1:3])
print('\ndata[0:2] = ', data[0:2,0])

data
[[1 2]
 [3 4]
 [5 6]]

data[row:row, col:col]
data[0,1] =  2

data[1:3]
 [[3 4]
 [5 6]]

data[0:2] =  [1 3]


In [55]:
#MATRIX AGGREGATION
print('data.max() = ', data.max())
print('data.min() = ', data.min())
print('data.sum() = ', data.sum())

data.max() =  6
data.min() =  1
data.sum() =  21

data.max(axis=0) =  [5 6]
data.max(axis=1)
[2 4 6]


In [57]:
data = np.array([[1,2], [5,3], [4,6]])
print('data')
print(data)

#Get max of each column
print('\ndata.max(axis=0) = ', data.max(axis=0))

#Get max of each row
print('data.max(axis=1)')
print(data.max(axis=1))

data
[[1 2]
 [5 3]
 [4 6]]

data.max(axis=0) =  [5 6]
data.max(axis=1)
[2 5 6]


In [59]:
data = np.array([[1,2], [3,4], [5,6]])
print('data')
print(data)

print('\ndata.T')
print(data.T)

data
[[1 2]
 [3 4]
 [5 6]]

data.T
[[1 3 5]
 [2 4 6]]


In [69]:
data = np.array([[1],[2],[3],[4],[5],[6]])
print('data')
print(data)

print('\ndata.reshape(2,3)')
print(data.reshape(2,3))

print('\ndata.reshape(3,2)')
print(data.reshape(3,2))

print('\ndata.reshape(-1)')
print(data.reshape(-1))

data
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]

data.reshape(2,3)
[[1 2 3]
 [4 5 6]]

data.reshape(3,2)
[[1 2]
 [3 4]
 [5 6]]

data.reshape(-1)
[1 2 3 4 5 6]


In [70]:
#N-Dimensional Array
cube = np.array([ [[1,2], [3,4]],
                  [[5,6], [7,8]]])
print(cube)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


![cube](https://jalammar.github.io/images/numpy/numpy-3d-array-creation.png)

In [75]:
#MEAN SQUARED ERROR
predictions = np.array([1, 1, 1])
labels = np.array([1, 2, 3])
print('predictions')
print(predictions)

print('\nlabels')
print(labels)

n = len(predictions)
error = (1/n) * np.sum(np.square(predictions - labels))
print('\n', error)

predictions
[1 1 1]

labels
[1 2 3]

 1.6666666666666665
